config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :user do
      resources :results
    end

  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}


    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end
      end
    end


    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs'
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/share/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="carousel-caption ">
			<h1 class="texto-car">COMIENZA UNA NUEVA VIDA Y ÚNETE AL MUNDO COMPETITIVO</h1>
				<br>
				<%= link_to "Comienza acá!", root_path(anchor: 'plans'), class: "btn btn-primary" %>
				<a href="<%= new_user_registration_path%>" class="btn btn-success">Regístrate!</a>
				<h2 class="texto-car font-weight-bold">Sigue rutinas de entrenamiento de fácil acceso, por entrenadores que quieren apoyar a los deportistas amateur de atletismo, diseñados según tu objetivo. Pudiendo observar tu progreso y como se compara con los demás deportistas.</h2>
		</div>
		<div class="carousel-item active">
			<%= image_tag("slide2.jpg",class: "d-block w-100", size: "800x800", alt: "First slide")%>
		</div>
		<div class="carousel-item">
			<%= image_tag("slide1.jpg",class: "d-block w-100", size: "800x800", alt: "Second slide")%>
		</div>
		<div class="carousel-item">
			<%= image_tag("slide3.jpg",class: "d-block w-100", size: "800x800", alt: "Third slide")%>
		</div>
	</div>
	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

app/views/share/_footerC.html.erb
<div class="container-fluid bottom" style="background-color: #2b2b2b">
	<div class="row">
		<div class="offset-md-1 col-md-7" style="color: #fff">
			<h5>COPYRIGHT 2019 - FELIPE MAHANA</h5>
		</div>
	</div>
</div>

app/views/share/_footerL.html.erb
<div class="container-fluid bottom footer">
	<div class="row">
		<div class="offset-md-1 col-md-3">
			<br>
			<h5>Mas Información</h5>
			<%= link_to "Contactos", contact_path %>
			<br>
			<%= link_to "Terminos y Condiciones",terms_and_conditions_path %>
		</div>
		<div class="offset-md-1 col-md-3">
			<br>
			<h5>Redes Sociales</h5>
			<a target="_blank" href="https://www.instagram.com">Instagram</a>
			<a target="_blank" href="https://www.facebook.com/">Facebook</a>
			<a target="_blank" href="https://twitter.com">Twitter</a>
		</div>
	</div>
</div>

app/views/share/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #42b649">
    <a class="navbar-brand" href="<%= root_path %> "><%= image_tag("logo.png", size: "45x45", alt: "Logo")%></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%# if current_user.admin? or current_user.professional?%>
          <% if can?(:create, :program) %>
            <li class="nav-item">
              <%= link_to "Contratos", user_contracts_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Programas", user_programs_path, class: 'nav-link'%>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? and current_user.role == 'guest'%>
          <li class="nav-item">
            <% if current_user.name.present? %>
              <%= link_to current_user.name, profile_path, class: 'nav-link' %>
            <% else %>
              <%= link_to current_user.email, profile_path, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% elsif user_signed_in? and current_user.role != 'guest'%>
          <li class="nav-item">
            <% if current_user.name.present? %>
              <%= link_to current_user.name, user_contracts_path, class: 'nav-link' %>
            <% else %>
              <%= link_to current_user.email, user_contracts_pathh, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
</nav>