config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :user do
      resources :results
    end

  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}


    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end
      end
    end


    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs'
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :contract
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new, :user_programs]
    before_action :set_program, only: [:edit, :show, :update]
    before_action :set_user, only: [:new, :edit, :show, :update]
    before_action :set_contract, only: [:new,:create, :edit, :show, :update]
    before_action :set_plan, only: [:new, :edit, :show, :update]
    before_action :program_params, only: [:create, :update]
    authorize_resource

    def user_programs
        @programs = Program.all
    end

    def new
        @program = Program.new
    end

    def edit

    end


    def show

    end

    def update
        @program.contract_id = params[:contract_id]
        @program.edited = true
        @program.update(program_params)
        if @program.update(program_params)
            redirect_to user_programs_path, notice: 'El programa se a actualizado con exito'
        else
            redirect_to user_programs_path, notice: 'El programa no se a actualizado'
        end
    end

    def create
        @program = Program.new(program_params)
        @program.contract = @contract
        @contract.pending = false
        #obteniendo al entrenador
        @program.coach_mail = current_user.email
        @program.coach_name = current_user.name

        if @program.save and @contract.save
             redirect_to user_contracts_path, notice: 'Se creo programa con exito'
        else
            redirect_to user_contracts_path, notice: 'No se pudo crear programa'
        end
    end

    private


    def program_params
		params.require(:program).permit(:training, :nutrition, :plan_id, :contract_id, :user_id)
	end

    def set_program
        @program = Program.find(params[:id])
    end

    def set_user
        @user = User.find(params[:user_id])
    end

    def set_contract
        @contract = Contract.find(params[:contract_id])
    end

    def set_plan
        @plan = Plan.find(params[:plan_id])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/edit.html.erb
<br><br><br>
<% if @plan.contract_type == 1%>
	<h3>Editar Plan Entrenamiento</h3>
<% elsif @plan.contract_type == 2 %>
	<h3>Editar de Plan Nutricional </h3>
<% else %>
	<h3>Editar Plan Entrenamiento y nutrición</h3>
<% end %>


<div class="row">
	<div class="col-md-4 mb-4">
		<div class="card card-new h-100 border-dark mb-3">
			<div class="card-header">
				<% if @user.name.present? %>
					<h5 class="card-title text-center"> <%= @user.name %> </h5>
				<% else %>
					<h5 class="card-title text-center"> <%= @user.email %> </h5>
				<% end %>
			</div>
			<div class="card-body">
				<% if @plan.contract_type == 1%>
					<p class="card-text">Tipo plan: Plan Entrenamiento</p>
				<% elsif @plan.contract_type == 2 %>
					<p class="card-text">Tipo plan: Plan Nutrición</p>
				<% else %>
					<p class="card-text">Tipo plan: Plan Entrenamiento con Nutrición </p>
				<% end %>
				<p class="card-text">Duracion plan: <%= @plan.duration %> Mes(es)</p>
				<p class="card-text">Descripcion: <%= @plan.description %> </p>
		 	</div>
		</div>
	</div>
	<div class="offset-md-2 col-md-4 mb-4">
		<div class="card card-new h-100 border-dark mb-3">
			<div class="card-header">
				<h5 class="card-title text-center"> Datos Cliente </h5>
			</div>
			<div class="card-body">
				<p class="card-text">Edad: <%= @contract.age %> </p>
				<% if @contract.sex == 1 %>
					<p class="card-text">Sexo: Masculino </p>
				<% else %>
					<p class="card-text">Sexo: Femenino </p>
				<% end %>
				<p class="card-text">Peso: <%= @contract.weight %> kg </p>
				<p class="card-text">Estatura: <%= @contract.height %> cms </p>
				<p class="card-text">Categoría: <%= @contract.category %> </p>
				<p class="card-text">Objetivo: <%= @contract.goal %> </p>
		 	</div>
		</div>
	</div>
</div>


<h4>Plan</h4>

<% if @plan.contract_type == 1 %>

	<div class="row">
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :entrenamiento %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50, placeholder: 'Ingrese Rutina Entrenamiento', class: 'form-control') %>
				<br>
				<%= form.submit 'Editar', class: 'btn btn-primary' %>
				<br>
				<%= link_to 'Volver a edición', user_programs_path %>
			<% end %>
		</div>
	</div>

<% elsif @plan.contract_type == 2 %>

	<div class="row">
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :nutrición %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50, placeholder: 'Ingrese Plan Nutricional', class: 'form-control') %>
				<br>
				<%= form.submit 'Editar', class: 'btn btn-primary' %>
				<br>
				<%= link_to 'Volver a edición', user_programs_path %>
			<% end %>
		</div>
	</div>

<% else %>

	<div class="row">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :entrenamiento %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50, placeholder: 'Ingrese Rutina Entrenamiento', class: 'form-control') %>
				<%=form.label :nutricion %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50, placeholder: 'Ingrese Plan Nutricional', class: 'form-control') %>
				<br>
				<%= form.submit 'Editar', class: 'btn btn-primary' %>
				<br>
				<%= link_to 'Volver a edición', user_programs_path %>
			<% end %>
	</div>
<% end %>

app/views/programs/new.html.erb
<br><br><br>
<% if @plan.contract_type == 1%>
	<h3>Realización de Plan Entrenamiento</h3>
<% elsif @plan.contract_type == 2 %>
	<h3>Realización de Plan Nutricional </h3>
<% else %>
	<h3>Realización de Plan Entrenamiento y nutrición</h3>
<% end %>


<div class="row">
	<div class="col-md-4 mb-4">
		<div class="card card-new h-100 border-dark mb-3">
			<div class="card-header">
				<% if @user.name.present? %>
					<h5 class="card-title text-center"> <%= @user.name %> </h5>
				<% else %>
					<h5 class="card-title text-center"> <%= @user.email %> </h5>
				<% end %>
			</div>
			<div class="card-body">
				<% if @plan.contract_type == 1%>
					<p class="card-text">Tipo plan: Plan Entrenamiento</p>
				<% elsif @plan.contract_type == 2 %>
					<p class="card-text">Tipo plan: Plan Nutrición</p>
				<% else %>
					<p class="card-text">Tipo plan: Plan Entrenamiento con Nutrición </p>
				<% end %>
				<p class="card-text">Duracion plan: <%= @plan.duration %> Mes(es)</p>
				<p class="card-text">Descripcion: <%= @plan.description %> </p>
		 	</div>
		</div>
	</div>
	<div class="offset-md-2 col-md-4 mb-4">
		<div class="card card-new h-100 border-dark mb-3">
			<div class="card-header">
				<h5 class="card-title text-center"> Datos Cliente </h5>
			</div>
			<div class="card-body">
				<p class="card-text">Edad: <%= @contract.age %> </p>
				<% if @contract.sex == 1 %>
					<p class="card-text">Sexo: Masculino </p>
				<% else %>
					<p class="card-text">Sexo: Femenino </p>
				<% end %>
				<p class="card-text">Peso: <%= @contract.weight %> kg </p>
				<p class="card-text">Estatura: <%= @contract.height %> cms </p>
				<p class="card-text">Categoría: <%= @contract.category %> </p>
				<p class="card-text">Objetivo: <%= @contract.goal %> </p>
		 	</div>
		</div>
	</div>
</div>


<h4>Plan</h4>

<% if @plan.contract_type == 1 %>

	<div class="row">
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :entrenamiento %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50, placeholder: 'Ingrese Rutina Entrenamiento', class: 'form-control') %>
				<br>
				<%= form.submit 'Crear', class: 'btn btn-success' %>
				<br>
				<%= link_to 'Volver a contratos', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% elsif @plan.contract_type == 2 %>

	<div class="row">
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :nutrición %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50, placeholder: 'Ingrese Plan Nutricional', class: 'form-control') %>
				<br>
				<%= form.submit 'Crear', class: 'btn btn-success' %>
				<br>
				<%= link_to 'Volver a contratos', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% else %>

	<div class="row">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :entrenamiento %> <br>
				<%=form.text_area(:training, rows: 10, cols: 40, placeholder: 'Ingrese Rutina Entrenamiento', class: 'form-control') %>
				<%=form.label :nutrición %> <br>
				<%=form.text_area(:nutrition, rows: 10, cols: 50, placeholder: 'Ingrese Plan Nutricional', class: 'form-control') %>
				<br>
				<%= form.submit 'Crear', class: 'btn btn-success' %>
				<br>
				<%= link_to 'Volver a contratos', user_contracts_path %>
			<% end %>
	</div>
<% end %>

app/views/programs/user_programs.html.erb
<br><br><br>
<h4>Tabla con usuarios y solicitud de edicion</h4>

<div class="user-programs table-responsive">
    <table class="table table-striped table-hover table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Usuario</th>
          <th>Plan</th>
          <th>Fecha Termino</th>
          <th>Duracion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @programs.order("created_at").each do |program| %>
          <% if current_user.email == program.coach_mail and program.edited == false %>
            <tr>
              <% if program.contract.user.name.present? %>
                <td><%= program.contract.user.name %></td>
              <% else %>
                <td><%= program.contract.user.email %></td>
              <% end %>
              <td>
                <% if program.contract.plan.contract_type == 1 %>
                  Plan Entrenamiento
                <% elsif program.contract.plan.contract_type == 2 %>
                  Plan Nutricional
                <% else %>
                  Plan Entrenamiento y Nutricional
                <% end %>
              </td>

              <td>
                <% end_date_contract=(program.contract.created_at+program.contract.plan.duration)%>
                <%= end_date_contract.strftime('%d/%m/%Y')  %>
              </td>

              <td>
                <%= program.contract.plan.duration %>
              </td>

              <td>
                <%= link_to "Editar", edit_plan_contract_user_program_path(program.contract.plan.id,program.contract.id,program.contract.user.id,program.id), :class=>"btn btn-primary" %>
                </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
</div>