config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :user do
      resources :results
    end

  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}


    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end
      end
    end


    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs'
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user

  #probando validacion
  #validates_numericality_of :hundred_mts, greater_than_or_equal_to: 9.5, message: 'hola'
  #validate :greater_than_or_equal_to

  #def greater_than_or_equal_to
  #  errors.add(:hundred_mts, 'ola')
  #end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_user
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET users/1/results
  def index
    @todos = Result.all
    @results = @user.results
    #@inicio_graf = params[:start].try(:to_date) || 180.days.ago.to_date
    #@fin_graf = params[:end].try(:to_date) || Date.current

    @inicio_graf = params[:start].try(:to_date).try(:beginning_of_month) || 180.days.ago.beginning_of_month
    @fin_graf = params[:end].try(:to_date).try(:end_of_month) || Date.today.end_of_month

    @range = (@inicio_graf..@fin_graf)

    @promedio_100 = (@todos.average(:hundred_mts))
    @promedio_100individual = (@results.average(:hundred_mts))
    @promedio_200 = (@todos.average(:two_hundred_mts))
    @promedio_200individual = (@results.average(:two_hundred_mts))
    @promedio_300 = (@todos.average(:three_hundred_mts))
    @promedio_300individual = (@results.average(:three_hundred_mts))
    @promedio_400 = (@todos.average(:four_hundred_mts))
    @promedio_400individual = (@results.average(:four_hundred_mts))
    @promedio_800 = (@todos.average(:eight_hundred_mts))
    @promedio_800individual = (@results.average(:eight_hundred_mts))
    @promedio_1000 = (@todos.average(:thousand_mts))
    @promedio_1000individual = (@results.average(:thousand_mts))
    @promedio_1500 = (@todos.average(:thousand_five_hundred_mts))
    @promedio_1500individual = (@results.average(:thousand_five_hundred_mts))
    @promedio_CT = (@todos.average(:cooper_test))
    @promedio_CTindividual = (@results.average(:cooper_test))
    @promedio_Squat = (@todos.average(:squat_rm))
    @promedio_Squatindividual = (@results.average(:squat_rm))
  end

  # GET users/1/results/1
  def show
  end

  # GET users/1/results/new
  def new
    @result = @user.results.build
  end

  # GET users/1/results/1/edit
  def edit
  end

  # POST users/1/results
  def create
    @result = @user.results.build(result_params)
    @result.date = DateTime.now.strftime "%d/%m/%Y"
    if @result.save
      redirect_to profile_path(), notice: 'Result was successfully created.'
      #redirect_to([@result.user, @result], notice: 'Result was successfully created.') ideal
    else
      render action: 'new'
    end
  end

  # PUT users/1/results/1
  def update
    if @result.update_attributes(result_params)
      redirect_to([@result.user, @result], notice: 'Result was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE users/1/results/1
  def destroy
    @result.destroy

    redirect_to user_results_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_result
      @result = @user.results.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def result_params
      params.require(:result).permit(:date, :hundred_mts, :two_hundred_mts, :three_hundred_mts, :four_hundred_mts, :eight_hundred_mts, :thousand_mts, :thousand_five_hundred_mts, :cooper_test, :squat_rm)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: [@result.user, @result]) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-text form-group">
    <%= f.label :cien_metros %>
    <em>(Seg)</em>
    <%= f.number_field :hundred_mts, min: 9.5, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'  %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :doscientos_metros %>
    <em>(Seg)</em>
    <%= f.number_field :two_hundred_mts, min: 19.2, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'  %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :trescientos_metros %>
    <em>(Seg)</em>
    <%= f.number_field :three_hundred_mts, min: 31.5, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :cuatrocientos_metros %>
    <em>(Seg)</em>
    <%= f.number_field :four_hundred_mts, min: 43.2, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :ochocientos_metros %>
    <em>(Seg)</em>
    <%= f.number_field :eight_hundred_mts, min: 101.2, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :mil_metros %>
    <em>(Seg)</em>
    <%= f.number_field :thousand_mts, min: 132, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :mil_quinientos_metros %>
    <em>(Seg)</em>
    <%= f.number_field :thousand_five_hundred_mts, min: 206, max: 1000, step: 0.1, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :test_de_cooper %>
    <em>(Mts)</em>
    <%= f.number_field :cooper_test, in: 500...5000, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <div class="field form-text form-group">
    <%= f.label :sentadilla_maxima %>
    <em>(Kg)</em>
    <%= f.number_field :squat_rm, in: 20...500, placeholder: 'Ingrese Resultado', class: 'form-control'   %>
  </div>
  <!--
  <div class="field form-text form-group">
    <%= f.label :date %><br />
    <%= f.date_select :date, class: 'datepicker' %>
  </div>
  -->
  <div class="actions">
    <%= f.submit "Crear Resultado", class: 'btn btn-success'%>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', [@result.user, @result] %> |
<%= link_to 'Back', user_results_path(@result.user) %>

app/views/results/index.html.erb
<br><br><br>

<div class="row">
  <div class="intervalo col-md-4">
    <h5>Intervalo Fechas:</h5>
    <input type="text" id="rangepicker" class="form-control" >
  </div>
  <% if can?(:create, :program) %>
    <div class="col-md-6 offset-md-2">
      <h5>Usuario:</h5>
      <div class="row">
        <% if @user.name.present? %>
          <div class="col-md-4">
            <p><%= @user.name %></p>
          </div>
          <div class="col-md-4">
            <p><%= @user.email %></p>
          </div>
        <% else %>
          <div class="col-md-4">
            <p><%= @user.email %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br>

<h3>Resultados</h3>

<div class="row">
  <div class="col-md-6">
    <br>
    <h4>100 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
  <% if @promedio_100.present? and @promedio_100individual.present? %>
    <p>El promedio general de 100 metros es de <b><%= "#{@promedio_100.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_100individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_100 < @promedio_100individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p>
  <% else %>
    <b>El usuario aun no tiene informacion para analisis de resultados</b>
  <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>200 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:two_hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:two_hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:two_hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_200.present? and @promedio_200individual.present? %>
      <p>El promedio general de 200 metros es de <b><%= "#{@promedio_200.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_200individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_200 < @promedio_200individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p >
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>300 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:three_hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:three_hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:three_hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_300.present? and @promedio_300individual.present? %>
      <p>El promedio general de 300 metros es de <b><%= "#{@promedio_300.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_300individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_300 < @promedio_300individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>400 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:four_hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:four_hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:four_hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_400.present? and @promedio_400individual.present? %>
      <p>El promedio general de 400 metros es de <b><%= "#{@promedio_400.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_400individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_400 < @promedio_400individual ? "lento" : "rapido"%></b> que los demás en esta categoría.   </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>800 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:eight_hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:eight_hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:eight_hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_800.present? and @promedio_800individual.present? %>
      <p>El promedio general de 800 metros es de <b><%= "#{@promedio_800.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_800individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_800 < @promedio_800individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>1000 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:thousand_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:thousand_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:thousand_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_1000.present? and @promedio_1000individual.present? %>
      <p>El promedio general de 1000 metros es de <b><%= "#{@promedio_1000.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_1000individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_1000 < @promedio_1000individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>1500 mts</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:thousand_five_hundred_mts)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:thousand_five_hundred_mts)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).minimum(:thousand_five_hundred_mts))},
    ], xtitle: "Fecha", ytitle: "Tiempo", suffix: " seg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_1500.present? and @promedio_1500individual.present? %>
      <p>El promedio general de 1500 metros es de <b><%= "#{@promedio_1500.round(2)}"%></b> segundos, mientras que tu promedio es de <b><%= "#{@promedio_1500individual.round(2)}"%></b> segundos, por lo que en general eres mas <b><%=  @promedio_1500 < @promedio_1500individual ? "lento" : "rapido"%></b> que los demás en esta categoría. </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>Test de Copper</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:cooper_test)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:cooper_test)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).maximum(:cooper_test))},
    ], xtitle: "Fecha", ytitle: "Distancia", suffix: "mts", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_CT.present? and @promedio_CTindividual.present? %>
      <p>El promedio general en el Test de Copper es de <b><%= "#{@promedio_CT.round(2)}"%></b> metros, mientras que tu promedio es de <b><%= "#{@promedio_CTindividual.round(2)}"%></b> metros, por lo que en general eres mas <b> <%=  @promedio_CT < @promedio_CTindividual ? "rapido" : "lento"%></b> que los demás en esta categoría.  </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
  <div class="col-md-6">
    <br>
    <h4>Sentadilla Máximo</h4>
    <%= line_chart [
      {name: "Peor Marca", data: (@results.group_by_month(:date, range: @range).minimum(:squat_rm)) },
      {name: "Mejor Marca", data: (@results.group_by_month(:date, range: @range).maximum(:squat_rm)) },
      {name: "Mejor Marca General", data: (Result.group_by_month(:date, range: @range).maximum(:squat_rm))},
    ], xtitle: "Fecha", ytitle: "Peso", suffix: " Kg", thousands: ".",decimal: ",", messages: {empty: "No hay Información"} %>
    <% if @promedio_Squat.present? and @promedio_Squatindividual.present? %>
      <p>El promedio general en la sentadilla máxima es de <b><%= "#{@promedio_Squat.round(2)}"%></b> Kilogramos, mientras que tu promedio es de <b><%= "#{@promedio_Squatindividual.round(2)}"%></b> Kilogramos, por lo que en general tienes<b>  <%=  @promedio_Squat < @promedio_Squatindividual ? "mas explosividad en las piernas" : "menos explosividad en las piernas"%></b> que los demás en esta categoría.  </p>
    <% else %>
      <b>El usuario aun no tiene información para análisis de resultados</b>
    <% end %>
  </div>
</div>

<%#= link_to 'New Result', new_user_result_path(params[:user_id]) %>
<div class="row">
  <div class="col-md-6 mb-4">
    <% if can?(:create, :program)%>
      <%= link_to 'Volver', user_contracts_path, class: 'btn btn-success' %>
    <% else %>
      <%= link_to 'Volver', profile_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>


<%= form_tag user_results_path, method: :get do %>
  <%= hidden_field_tag :start %>
  <%= hidden_field_tag :end %>
<% end %>

<script>
  $("#rangepicker").daterangepicker({
    startDate: moment("<%= l @inicio_graf, format: '%Y-%m-%d' %>"),
    endDate: moment("<%= l @fin_graf, format: '%Y-%m-%d' %>"),
    "locale": {
        "format": "DD/MM/YYYY",
        "separator": " - ",
        "applyLabel": "Aplicar",
        "cancelLabel": "Cancelar",
        "fromLabel": "De",
        "toLabel": "Hasta",
        "customRangeLabel": "Custom",
        "daysOfWeek": [
            "Do",
            "Lu",
            "Ma",
            "Mi",
            "Ju",
            "Vi",
            "Sá"
        ],
        "monthNames": [
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"
        ],
        "firstDay": 1
    }
  }, function(start, end, label) {
    $("#start").val(start.format('YYYY-MM-DD'));
    $("#end").val(end.format('YYYY-MM-DD'));

    $("form").submit();
  });
</script>

app/views/results/new.html.erb
<br><br><br>
<h1>Nuevo Resultado</h1>


<%= render 'form' %>

<%#= link_to 'Back', user_results_path(@result.user) %>
<br>
<div class="row">
  <div class="col-md-6 mb-4">
    <%= link_to 'Volver a perfil', profile_path %>
  </div>
</div>

app/views/results/show.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<h4>Comprobacion</h4>

<div class="row">
	<div class="col-md-6 mb-4">
		<h5>Datos Resultado</h5>
		<div class="card">
			<div class="card-body">
				<h5 class="card-title"> Fecha: <%= @result.date %> </h5>
				<p class="card-text"> 100 mts:<%= @result.hundred_mts %> </p>
				<p class="card-text"> 200 mts: <%= @result.two_hundred_mts %> </p>
				<p class="card-text"> 300 mts: <%= @result.three_hundred_mts %> </p>
				<p class="card-text"> 400 mts: <%= @result.four_hundred_mts %> </p>
				<p class="card-text"> 800 mts: <%= @result.eight_hundred_mts %> </p>
				<p class="card-text"> 1000 mts: <%= @result.thousand_mts %> </p>
				<p class="card-text"> 1500 mts: <%= @result.thousand_five_hundred_mts %> </p>
				<p class="card-text"> Test cooper: <%= @result.cooper_test %> </p>
				<p class="card-text"> sentadillas: <%= @result.squat_rm %> </p>
		 	</div>
		</div>
	</div>
</div>

<!--
<p>
  <b>Fecha:</b>
  <%= @result.date %>
</p>

<p>
  <b>100 mts:</b>
  <%= @result.hundred_mts %>
</p>

<p>
  <b>200 mts:</b>
  <%= @result.two_hundred_mts %>
</p>

<p>
  <b>300 mts:</b>
  <%= @result.three_hundred_mts %>
</p>

<p>
  <b>400 mts:</b>
  <%= @result.four_hundred_mts %>
</p>

<p>
  <b>800 mts:</b>
  <%= @result.eight_hundred_mts %>
</p>

<p>
  <b>1000 mts:</b>
  <%= @result.thousand_mts %>
</p>

<p>
  <b>1500 mts:</b>
  <%= @result.thousand_five_hundred_mts %>
</p>

<p>
  <b>Test de Cooper:</b>
  <%= @result.cooper_test %>
</p>

<p>
  <b>Squat rm:</b>
  <%= @result.squat_rm %>
</p>
-->

<%#= link_to 'Edit', edit_user_result_path(@result.user, @result) %>
<%#= link_to 'Back', user_results_path(@result.user) %>

<%= link_to 'Volver perfil', profile_path %>