config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    resources :user do
      resources :results
    end

  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}


    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end
      end
    end


    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs'
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :contracts, dependent: :destroy
  	has_many :users, through: :contracts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :results, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contracts, dependent: :destroy
  has_many :plans, through: :contracts, dependent: :destroy

  enum role: [:guest ,:professional, :admin]
  #paginates_per 8
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, only: [:user_contracts, :profile]
  def index
    @plans = Plan.all
  end

  def profile

  end

  def contact

  end

  def terms_and_conditions

  end

  def user_contracts
    @users = User.all
    #Kaminary
    # @users = User.order(:created_at).page(params[:page])
    # cuenta los admin y los que cambiaron de estado
    # @user.each do |users|
    #   if users.role == 'guest'
    #     @users = User.order(:created_at).page(params[:page]).per(8)
    #   end
    # end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/contact.html.erb
<h5>Datos Contacto</h5>

<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</div>
<div>Velit autem, quisquam dolorum facilis ullam praesentium doloribus error nobis facere.</div>
<div>Tempora aliquam amet labore blanditiis deserunt totam in eligendi perspiciatis modi consectetur fugiat deleniti officiis voluptatum repellat voluptates dolores expedita eveniet iure, delectus veritatis. Optio alias, nam esse. Alias, ex!</div>

app/views/plans/index.html.erb
<div class="container">
	<div class="row">
		<div class="offset-md-5 col-md-3">
			<h5>Entrenamiento en línea</h5>
		</div>
		<p>Los Planes de entrenamiento y/o nutrición entregan rutinas personalizada, pensada en tus metas personales dentro del atletismo, esto se logra mediante entrenadores que desean ayudar e incrementar el nivel de competición en chile dentro del circulo amateur, estas rutinas no necesitas tener contacto físico con tu entrenador, se te entregara el contacto directo de este, con el cual podrán ir revisando el progreso y actualizando rutinas o planes nutricionales. Todos los planes cuentan con una sección en la cual podrás agregar tus marcas personales dentro de las categorías disponibles y poder ver el progreso de tus mejores y peores marcas dentro del mes, también esta sección cuenta con las mejores marcas de todos dentro de la plataforma y el promedio de sus resultados, con el fin de tener una comparativa y ver en el nivel que te encuentras.
		</p>
	</div>
</div>

<div id="plans" class="row">
	<% @plans.order("duration").each do | plans | %>
		<div class="col-md-4 mb-4">
			<div class="card h-100 border-success mb-3">
				<div class="card-header text-center">
					<% if plans.contract_type == 1%>
						<h5 class="card-title"> Plan Entrenamiento </h5>
					<% elsif plans.contract_type == 2 %>
						<h5 class="card-title"> Plan Nutrición </h5>
					<% else %>
						<h5 class="card-title"> Plan Entrenamiento con Nutrición </h5>
					<% end %>
				</div>
				<% if plans.contract_type == 1%>
					<%= image_tag("cart1.jpg",class: "card-img-top", size: "200x200", alt: "...")%>
				<% elsif plans.contract_type == 2 %>
					<%= image_tag("cart2.jpg",class: "card-img-top", size: "200x200", alt: "...")%>
				<% else %>
					<%= image_tag("cart3.jpg",class: "card-img-top", size: "200x200", alt: "...")%>
				<% end %>
					<div class="card-body card-index text-center">
						<!--<p class="card-text">Precio: $<%#= @plan.price %> </p>-->
						<p class="card-text">La duracion del plan <%= plans.duration %> mes(es)</p>
						<p class="card-text text-left"><%= plans.description %> </p>
						<a href="<%= new_plan_contract_path(plans)%>" class="btn btn-success">Contratar</a>
					</div>
			</div>
		</div>
	<% end %>
</div>


<div class="container">
	<div class="row">
		<div class="offset-md-5 col-md-3">
			<h5>Preguntas Frecuentes</h5>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>
	</div>
</div>

app/views/plans/profile.html.erb
<br><br><br>
<div class="perfil">
	<% if current_user.contracts.present? %>
		<div class="row">
			<div class="col-md-6 mb-4 offset-md-3">
				<div class="card h-100 border-dark mb-3">
					<div class="card-header">
						<h5 class="card-title text-center">Perfil</h5>
					</div>
					<div class="card-body">
						<% if current_user.name.present? %>
							<p class="card-text">  Nombre: <%= current_user.name %> </p>
							<p class="card-text">  Correo: <%= current_user.email %> </p>
						<% else %>
							<p class="card-text">  Correo: <%= current_user.email %> </p>
						<% end %>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-6 mb-1">
							<div class="card h-100 border-dark mb-3">
								<div class="card-header">
									<h5>Datos Personales</h5>
								</div>
								<div class="card-body card-datos">
									<p class="card-text">Edad: <%= current_user.contracts.last.age %></p>
									<% if current_user.contracts.last.sex == 1 %>
										<p class="card-text"> Sexo: Masculino </p>
									<% else %>
										<p class="card-text">Sexo: Femenino </p>
									<% end %>
										<p class="card-text">Peso: <%= current_user.contracts.last.weight %> kg</p>
										<p class="card-text">Estatura: <%= current_user.contracts.last.height %> cms </p>
								</div>
								<!-- Parece traer problemas-->
								<%# if current_user.contracts.last.programs.last.present? %>
									<div class="card-footer ">
										<%= link_to "Editar Datos", edit_plan_contract_path(current_user.plan_ids ,current_user.contract_ids), class: "btn btn-outline-dark" %>
									</div>
								<%# end %>
							</div>
					</div>
					<div class="col-md-6 ">
							<div class="card h-100 border-dark mb-3">
								<div class="card-header">
									<h5>Datos Entrenador</h5>
								</div>
								<div class="card-body card-datos">
									<% if current_user.contracts.last.programs.last.try(:coach_name).present? %>
										<p class="card-text">Nombre: <%= current_user.contracts.last.programs.last.coach_name %></p>
										<p class="card-text">Correo: <%= current_user.contracts.last.programs.last.coach_mail %></p>
									<% elsif current_user.contracts.last.programs.last.try(:coach_mail).present? %>
										<p class="card-text">Correo: <%= current_user.contracts.last.programs.last.try(:coach_mail) %></p>
									<% else %>
										<p class="card-text">No tiene enrenador asociado</p>
									<% end %>
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>

	<br>
		<div class="row">
			<div class="col-md-5 offset-md-1">
				<div class="btn-group" role="group">
					<%= link_to "Agregar Resultados", new_user_result_path(current_user.id), :class=>"btn btn-success"%>
					<%= link_to "Visualizar Estadisticas", user_results_path(current_user.id), :class=>"btn btn-outline-success"%>
					<%# if current_user.results.present? %>
						<!--En algun lado cambie el orden de last a first -->
						<%#= link_to "Visualizar Resultado", user_result_path(current_user.id,current_user.results.first.id), :class=>"btn btn-outline-success"%>
					<%# end %>
				</div>
			</div>
		</div>

<br>

		<div class="row">
			<div class="col-md-12">
				<h4>Entrenamiento</h4>
				<% fecha_actual = Time.now %>
				<!--if program present-->
				<% if current_user.contracts.last.programs.last.present? %>
					<% fecha_inicial = current_user.contracts.last.programs.last.created_at%>
					<!--Borrar-->
					<%#= fecha_inicial.strftime('%d/%m/%Y') %>
					<!---->
					<% unless current_user.contracts.last.plan.nil? %>
						<% duration_plans_month=current_user.contracts.last.plan.duration.month %>
					<% end %>
					<!---->
					<% fecha_vencimiento = fecha_inicial + duration_plans_month %>
					<%#= fecha_vencimiento.strftime('%d/%m/%Y') %>
					<!--if FA<FV-->
					<% if fecha_actual < fecha_vencimiento %>
						<% if current_user.contracts.last.try(:programs).present? %>
							<% if current_user.contracts.last.plan.contract_type==1 %>
								<div class="row">
									<div class="col-md-6 mb-4">
										<div class="card border-dark mb-3">
											<div class="card-header">
												<h5 class="card-title text-center">Rutina entrenamiento</h5>
											</div>
											<div class="card-body">
												<p class="card-text"><%= simple_format(current_user.contracts.last.programs.last.training) %></p>
											</div>
										</div>
									</div>
								</div>
							<% elsif current_user.contracts.last.plan.contract_type==2 %>
								<div class="row">
									<div class="col-md-6 mb-4">
										<div class="card border-dark mb-3">
											<div class="card-header">
												<h5 class="card-title text-center">Plan Nutricional</h5>
											</div>
											<div class="card-body">
												<p class="card-text"><%= simple_format(current_user.contracts.last.programs.last.nutrition) %></p>
											</div>
										</div>
									</div>
								</div>
							<% else %>
								<div class="row">
									<div class="col-md-6 mb-1">
										<div class="card border-dark mb-3">
											<div class="card-header">
												<h5 class="card-title text-center">Rutina entrenamiento</h5>
											</div>
											<div class="card-body">
												<p class="card-text"><%= simple_format(current_user.contracts.last.programs.last.training) %></p>
											</div>
										</div>
									</div>
									<div class="col-md-6 ">
										<div class="card border-dark mb-3">
											<div class="card-header">
												<h5 class="card-title text-center">Plan Nutricional</h5>
											</div>
											<div class="card-body">
												<p class="card-text"><%= simple_format(current_user.contracts.last.programs.last.nutrition) %></p>
											</div>
										</div>
									</div>
								</div>
							<% end %>
						<% end %>
					<!--else FA<FV(82)-->
					<% else %>
						<div class="row">
							<div class="col-md-6 mb-6">
								<div class="card border-dark bg-info mb-3">
									<div class="card-body ">
										<h5 class="card-title">Perfil Vencido</h5>
										<p class="card-text">Tu plan se encuentra vencido, por favor actualizar</p>
									</div>
									<div class="card-footer ">
										<%= link_to "Actualizar acá!", root_path(anchor: 'plans'), class: "btn btn-light" %>
									</div>
								</div>
							</div>
						</div>
					<!--end FA<FV(82)-->
					<% end %>
				<!--else program present(71)-->
				<% else %>
					<div class="row">
						<div class="col-md-6 mb-6">
							<div class="card border-dark mb-3">
								<div class="card-body">
									<p class="card-text">No tiene rutina de entrenamiento</p>
								</div>
							</div>
						</div>
					</div>
				<!--end program present(71)-->
				<% end %>
			</div>
		</div>
	<% else %>
		<div class="col-md-6 mb-4 offset-md-4">
			<div class="card border-danger bg-warning mb-3 " style="max-width: 18rem;">
	  		<div class="card-header">Perfil</div>
	  			<div class="card-body text-danger">
	    			<h5 class="card-title">Perfil No Encontrado</h5>
	    			<p class="card-text">Usted no tiene contratado una rutina, por lo que no tiene acceso a los datos de perfil y analizáis de resultados, si le gustaría iniciar uno, apreté el siguiente botón para revisar los planes.</p>
	  			</div>
					<div class="card-footer ">
						<%= link_to "Comienza acá!", root_path(anchor: 'plans'), class: "btn btn-danger" %>
					</div>
			</div>
		</div>
	<%end%>
</div>
<br>

app/views/plans/terms_and_conditions.html.erb
<h5>Terminos y Condiciones</h5>

<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa excepturi quo ipsum laborum illum repudiandae ut qui, autem odit magnam expedita aperiam reprehenderit distinctio ipsam, cum velit? Itaque animi, laborum.</div>
<div>Maxime inventore omnis voluptate error quos veniam aut, eius debitis eligendi quam unde quis excepturi quia minima architecto, nesciunt rerum. Nihil necessitatibus minus consectetur eligendi tenetur commodi, vitae, beatae odio?</div>
<div>Et obcaecati cupiditate harum, nam quos consequatur praesentium, non earum quasi quibusdam magnam laboriosam aperiam, amet est eveniet, blanditiis enim ex quia repudiandae accusamus dolore nobis repellat voluptates quis. Aliquid!</div>
<div>Repellendus modi fuga unde eveniet dolor distinctio voluptates, quia nobis necessitatibus dolore repellat, autem eligendi ullam quod deleniti. Culpa, praesentium quos tempore eum quia dignissimos sunt, eveniet exercitationem numquam! Maxime!</div>
<div>Aspernatur itaque doloremque facilis eveniet sint eligendi quaerat officiis, provident officia porro ipsum repudiandae rerum odio quasi. Voluptate vel minus aspernatur ab eveniet, odio vitae velit inventore, quia tempore totam!</div>

app/views/plans/user_contracts.html.erb
<br>
<br>
<br>
<h4>Usuarios con planes pendientes</h4>
<div class="user_contract table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Usuario</th>
        <th>Plan</th>
        <th>Fecha Contrato</th>
        <th>Meses</th>
        <th>Categoría</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.order("created_at").each do |user| %>
        <% if user.contracts.present? and user.contracts.last.pending == true %>
          <tr>
            <% if user.name.present? %>
              <td><%= user.name %></td>
            <% else %>
              <td><%= user.email %></td>
            <% end %>
            <td>
              <% unless user.contracts.last.nil? %>
                <% unless user.contracts.last.plan.nil? %>
                  <% if user.contracts.last.plan.contract_type == 1%>
                    Plan Entrenamiento
                  <% elsif user.contracts.last.plan.contract_type == 2 %>
                    Plan Nutricional
                  <% else %>
                    Plan Entrenamiento y Nutrición
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <!--start date-->
            <td>
                <% unless user.contracts.last.nil? %>
                  <% start_date_conract=user.contracts.last.created_at %>
                  <%#= user.contracts.last.created_at %>
                  <%= user.contracts.last.created_at.strftime('%d/%m/%Y') %>
                  <%#= user.contracts.last.start_date%>
                <% end %>
            </td>
            <!--duracion-->
            <td>
              <% unless user.contracts.last.nil? %>
                <% unless user.contracts.last.plan.nil? %>
                  <% duration_plans_month=user.contracts.last.plan.duration.month %>
                  <%= user.contracts.last.plan.duration %>
                <% end %>
              <% end %>
            </td>
            <!--termino
            <td>
              <% end_date_contract=(start_date_conract+duration_plans_month)%>
              <%= end_date_contract.strftime('%d/%m/%Y')  %>
              <%#= user.contracts.last.end_date%>
            </td>-->

            <!--Categoria-->
            <td>
              <% unless user.contracts.last.nil? %>
                <%= user.contracts.last.category.to_s %>
              <% end %>
            </td>

            <td>
              <div class="btn-group" role="group">
                <%= link_to "Realizar", new_plan_contract_user_program_path(user.contracts.last.plan.id,user.contracts.last.id,user.id), :class=>"btn btn-outline-success"%>
                <%= link_to "Visualizar", user_results_path(user.id), :class=>"btn btn-outline-success"%>
              </div>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <!--Kaminary-->
  <%#= paginate @users, window:1, left:0, right: 1 %>
</div>